### PR TITLE
Wrote tests for rest/providers/remove

### PR DESCRIPTION
**Pull request by stanislavkozlovski**
#100

### CODE REVIEW

**Comment by stanislavkozlovski** [comment]
`>       if web.ctx.env["HTTP_HOST"] == 'localhost:8080' or open_d == "true":

E       AttributeError: 'ThreadedDict' object has no attribute 'env'`

Why do the web.header() and now this web.ctx.env give errors? Is there something wrong with the web module or is it from the project?
What should I do with this?

**Comment by cglewis** [comment]
@Enether here's how `web.ctx` works: http://webpy.org/cookbook/ctx

**Comment by stanislavkozlovski** [comment]
I read it but I don't understand why web.ctx.env and web.header() give out errors.
Do they require the server to be running and to have taken a request?

**Comment by cglewis** [comment]
I'm not exactly sure how to best test this, but I don't think you need a running server, just a `web.ctr` or `web.header` object that is globally set and accessible?

from the link:

```
web.ctx is based on the class threadeddict a.k.a. ThreadedDict
```

so my guess would be that the right way to test this would be to create a web.ctx object globally (or perhaps part of `self`?) that inherits from ThreadedDict and has the `.env` member set to the correct value, in this case a dict (ThreadedDict?) with the key `HTTP_HOST`.  

but that's all just a guess.

**Comment by cglewis** [comment]
I'm ok with it being put in a try/except for now if that makes the tests pass. but maybe add a comment about this behavior.

**Comment by stanislavkozlovski** [comment]
Thanks for the advice or 'guess' haha, will do!

**Review by cglewis — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
