### PR TITLE
Added build files to .gitignore

### PR DESCRIPTION
**Pull request by luciddr34m3r**
Added folders related to project build to .gitignore file.
#118

### CODE REVIEW

**Review by cglewis — CHANGES_REQUESTED** [review]
thanks! please add yourself to `AUTHORS`

**Comment by luciddr34m3r** [comment]
Added to authors file.

**Comment by cglewis** [comment]
please sort authors alphabetically, thanks!

**Review by cglewis — APPROVED** [review]

**Comment by luciddr34m3r** [comment]
Done

**Pull request merged**
