### PR TITLE
Basic integration test for listing providers

### PR DESCRIPTION
**Pull request by sshadmand**
So I did a basic integration tests that checks for 200 and an empty dict (since none was in the filesystem). Not sure if that is what you were looking for. LMK

As a note, it may be a good idea to create more unit tests instead of integration tests. That way you have more control over checking individual functionality of the code (and an ability to mock out 3rd party of out of scope functions). I haven't used pytest before so I will have to see if I can mock, and create a request factory to go that route.

### CODE REVIEW

**Comment by cglewis** [comment]
yeah, i started down that road using testApp from paste as a fixture to mock the wsgi app, which worked ok, but ran into some weirdness so I reverted back to a more integration-like setup.  if you come across a clever way to do with mock objects though, i'm all over it.  also since the number of tests for this project at this point are pretty minimal, i'd be open to changing test frameworks as well if you've a good one in mind that makes this easy.

**Comment by cglewis** [comment]
@sshadmand the tests look good, and definitely checks I'd like to have, but I'm also looking for coverage (which I seem to have broken my codecov integration last night, so need to fix that).  using the arguments from `make test` the testing framework outputs which lines are covered or missed per file, so in this case, `rest/providers/list_all` I would hope for additional tests that would cover the remaining lines that aren't covered, particularly 13-22:

```
/vcontrol/vcontrol/rest/providers/list_all.py             16     10    38%   13-22
```

**Comment by sshadmand** [comment]
Got it. Thanks for the info.

Just as an FYI, and for reference, the testing framework I have used in the past is "PyUnit" https://docs.python.org/2/library/unittest.html

Which come with mocks and patches:
https://docs.python.org/2.7/library/unittest.html?highlight=mock

**Comment by cglewis** [comment]
closing in favor of #115

**Pull request closed without merging**
