### PR TITLE
Added unit tests for test_shutdown.py

### PR DESCRIPTION
**Pull request by stanislavkozlovski**
If it's not correct, please point me in the right direction.

### CODE REVIEW

**Comment by cglewis** [comment]
@Enether looks like a good start, thanks! However the test you added is failing, try running `make test` from inside the vcontrol directory after you've cloned it down (note you'll need docker).

```
../tests/test_shutdown.py::test_create_machine_shutdown FAILED
```

```
================================================================== FAILURES ===================================================================
________________________________________________________ test_create_machine_shutdown _________________________________________________________

    def test_create_machine_shutdown():
        """ tests the ShutdownMachineR class for proper shutting down"""
        test_machine = 'foo'
        shutdown_machine_r = ShutdownMachineR()

>       assert shutdown_machine_r.GET(test_machine) == UNSUCCESSFUL_SHUTDOWN_MESSAGE

../tests/test_shutdown.py:9: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../vcontrol/rest/machines/shutdown.py:12: in GET
    web.header('Access-Control-Allow-Origin', self.allow_origin)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

hdr = 'Access-Control-Allow-Origin', value = '', unique = False

    def header(hdr, value, unique=False):
        """
        Adds the header `hdr: value` with the response.

        If `unique` is True and a header with that name already exists,
        it doesn't add a new one.
        """
        hdr, value = safestr(hdr), safestr(value)
        # protection against HTTP response splitting attack
        if '\n' in hdr or '\r' in hdr or '\n' in value or '\r' in value:
            raise ValueError, 'invalid characters in header'

        if unique is True:
            for h, v in ctx.headers:
                if h.lower() == hdr.lower(): return

>       ctx.headers.append((hdr, value))
E       AttributeError: 'ThreadedDict' object has no attribute 'headers'

/usr/local/lib/python2.7/dist-packages/web/webapi.py:297: AttributeError
===================================================== 1 failed, 4 passed in 0.89 seconds ======================================================
make: *** [test] Error 1
```

I'd go check the tests that were written for `info` in `test_rest.py` for examples to help you out.

**Comment by stanislavkozlovski** [comment]
I may be wrong but I suspect the problem is from the webapi.py module and not the tests?
I can't see what's wrong

**Comment by cglewis** [comment]
the `webapi.py` is not my code, it's part of the `web.py` library which this project is using.  I believe the issue is related to the header check and the object being sent in the test doesn't have the header object.

https://github.com/CyberReboot/vcontrol/blob/master/vcontrol/rest/machines/shutdown.py#L12

Note how in `info`, the header was put in a try/except which might solve this problem for you as well:

https://github.com/CyberReboot/vcontrol/blob/master/vcontrol/rest/commands/info.py#L12

**Comment by stanislavkozlovski** [comment]
But the object that's passed does not have any relation to the web.header() function. Regardless, changed it as you suggested :)

**Comment by cglewis** [comment]
yeah seems like a weird quirk with `web.py`.  looks like it fixed that test, but your other `test_status_command_fail` is still failing, which may no longer be necessary to even have.

**Review by cglewis — APPROVED** [review]
thanks!

**Pull request merged**
